# application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heroesdb
    username: app_user
    password: secretpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
